### metaDataWorkflowTestingA

##### Documents/Term/OncoSplice/metaProcessing

##### February 23, 2023

#### Test steps of meta workflow

####  PATHS & DEPENDENCIES

In [1]:
##import sys,string,os,re
##sys.path.insert(1, os.path.join(sys.path[0], '..')) ### ##import parent dir dependencies
###import altanalyze.unique as unique

import sys,string,os
sys.path.append('/Users/schh5o/Library/Python/3.7/lib/python/site-packages')
import pandas as pd
import numpy as np

##import unique
##import export
##import junctionGraph
##from stats_scripts import statistics

import math
import traceback
import collections

#### IMPORT A (PSI) DATA FILE TO USE FOR TESTING

In [2]:
fn1 = 'PSI_data_for_metaTesting.txt'

# --- Read in PSI data file to use for testing ---

delimChar ='\t'
fn = fn1

PSIdata = pd.read_table( fn, sep=delimChar, comment='#', header=0,index_col=0)
print( PSIdata.shape )

PSIdata_SampleNames = list(PSIdata.columns)
print(PSIdata_SampleNames)

(100, 27)
['SRS718908', 'SRS718980', 'SRS718910', 'SRS718911', 'SRS718914', 'SRS718915', 'SRS718916', 'SRS718917', 'SRS718930', 'SRS718931', 'SRS718933', 'SRS718937', 'SRS718939', 'SRS718940', 'SRS718944', 'SRS718945', 'SRS718951', 'SRS718952', 'SRS718955', 'SRS718956', 'SRS718957', 'SRS718975', 'SRS718958', 'SRS718959', 'SRS874618', 'SRS874619', 'SRS874620']

In [3]:
#PSIdata.shape
PSIdata.head()

,SRS718908,SRS718980,SRS718910,SRS718911,SRS718914,SRS718915,SRS718916,SRS718917,SRS718930,SRS718931,...,SRS718952,SRS718955,SRS718956,SRS718957,SRS718975,SRS718958,SRS718959,SRS874618,SRS874619,SRS874620
UID,,,,,,,,,,,,,,,,,,,,,
C1orf112:ENSG00000000460:E7.5-I7.1|ENSG00000000460:E7.5-E9.2,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
C1orf112:ENSG00000000460:E8.2-E9.1|ENSG00000000460:E7.5-E9.2,0.000000,0.125000,NaN,0.000000,0.054054,0.000000,0.052632,0.052632,0.000000,0.089286,...,0.000000,0.000000,0.022727,0.000000,0.035714,0.020000,0.000000,0.033898,NaN,NaN
C1orf112:ENSG00000000460:E7.5-E9.2|ENSG00000000460:E7.5_169764353-E9.1_169768059,1.000000,0.875000,NaN,0.888889,0.945946,0.916667,0.947368,0.763158,1.000000,0.910714,...,1.000000,0.964286,0.977273,0.894737,0.928571,0.980000,0.850000,0.898305,NaN,NaN
C1orf112:ENSG00000000460:I7.1-E8.1|ENSG00000000460:E7.5-E9.2,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
FGR:ENSG00000000938:E1.3-E4.1|ENSG00000000938:E3.2-E4.1,0.900222,0.683511,0.516854,0.673846,0.517358,0.533248,0.459436,0.518469,0.561564,0.574814,...,0.648855,0.527397,0.450704,0.410750,0.440000,0.603865,0.591568,0.460984,0.530612,0.617647


####  IMPORT UserMetaData AND PERFORM SOME BASIC CHECKS

In [10]:
# ----  VERSION FOR DEBUGGING  -----

def importUserMetaData2(fn,delimChar='\t', *args, SamplesList=None):
    """Import metadata that can be used for among sample/cell group comparisons"""
    """Input arguments are path/filename for the metadata and the delimiter used in the file"""
    """Optionally, can provide a list of sample names to check the meta file sample against"""

    """Top row of input file must be meta variable names and first column must be the sample identifier variable"""
    
    """ return as pandas DataFrame.  Sample identifiers in column 1 are NOT moved to row index position """  
    
    import pandas as pd
    
    try:
        mt = pd.read_table(fn,sep=delimChar,header=0,comment='#')
    except:
        print ("A problem occurred importing the metadata file:",fn)
        return None

#   File should have >1 row and > 1 column
    if mt.shape[0]==1:
        print( 'Only 1 row read from metadata file',fn,' please check file')
        return None
    elif mt.shape[1]==1:
        print( 'Only 1 column read from metadata file',fn,' please check file and delimiter')
        return None
        
#   If SamplesList was provided, check that contents of column 1 is 1-1 match to contents of Samples
#   if SamplesList is None:
#        print('Sample Names not provided')
    if SamplesList is not None:
#        print( 'Sample names provided')
        if SamplesList.__class__ != list:
            print( 'Sample names object not a list, sample names check not done')
            return mt
#        print('Checking for 1-1 match between metadata column 1 and Samples')
        UserMetaDataSamps = list( mt.iloc[:, 0] )
        UserMetaDataSamps.sort()
        SamplesList.sort()
#        print('UMDSamps:',UserMetaDataSamps)
#        print('Samples:',Samples)
        if UserMetaDataSamps != SamplesList:
            print('Identifiers in column 1 of metadata file',fn,'are not 1-1 match to identifiers in SamplesList or data matrix')
        
    return mt

In [4]:
from importUserMetaData2 import importUserMetaData2

In [5]:
fn='TestMeta1.txt'
delimChar ='\t'
md1 = importUserMetaData2(fn,delimChar)
print( md1.shape )
md1.head()

(27, 12)

,SRA_Sample_ID,150-MISTIQ-Cohort,Leucegene_Sample_ID,AltAnalyze_ID,Analyzed_Sets,Tissue_Source,QC,Patient_Age,Patient_Sex,RUNX1_fusions,PML-RARA_fusions,EVI1_fusions
0,SRS718908,False,04H061,SRS718908.bed,Training,Bone marrow,PASS,69,F,0,0,UNK
1,SRS718980,False,04H016,SRS718908.bed,Training,Bone marrow,PASS,70,F,NOVEL,UNK,UNK
2,SRS718910,False,04H061,SRS718910.bed,Training,Bone marrow,PASS,38,F,0,0,UNK
3,SRS718911,False,07H144,SRS718911.bed,Training,Bone marrow,PASS,53,M,NOVEL,0,UNK
4,SRS718914,False,09H016,SRS718914.bed,Training,Leukapheresis,PASS,64,F,UNK,0,UNK

In [6]:
fn='TestMeta3.txt'
delimChar ='\t'
md2 = importUserMetaData2(fn,delimChar)
display(md2)

A problem occurred importing the metadata file: TestMeta3.txt

None

In [7]:

fn='TestMeta2.txt'
delimChar =','
md3 = importUserMetaData2(fn,delimChar)
display(md3)

Only 1 column read from metadata file TestMeta2.txt  please check file and delimiter

None

In [8]:
fn='TestMeta1.txt'
delimChar ='\t'
samps = ['s1','s2','s3']
md4 = importUserMetaData2(fn,delimChar,SamplesList=samps)
#md4.head()

Identifiers in column 1 of metadata file TestMeta1.txt are not 1-1 match to identifiers in SamplesList or data matrix

In [9]:
fn='TestMeta1.txt'
delimChar ='\t'
samps = list(md1['SRA_Sample_ID'])
md5 = importUserMetaData2(fn,delimChar,SamplesList=samps)
# runs OK
#display(md5)

### At this point... 
### A-- you can use variable(s) in the UserMetaData object to define groups and proceed with an analysis, or,
### B-- the user may provide a TestCov(ariate) file to specify comparisons, possibly including data fitering.

## <font color='red'>Pursue B</font>


### IMPORT Test-Covariate FILE AND PERFORM SOME BASIC CHECKS

In [10]:
def importTestCovFile2(fn,delimChar='\t', *args, metaDF=None):
    """Import TestCov(ariate) file for user-specified statistical testing"""
    """Input arguments are path/filename and the delimiter used in the file"""
    """Optionally, can provide a metadata dataframe to perform additional checks on the TestCov file contents"""

    """TestCov file must: have 3 columns and NOT have a header row"""
    """General form of a row is metavariable name, role/use of metavariable, and (comma-separated) corresponding values"""
    
    
    """ returns a pandas DataFrame """  
    
    import pandas as pd
    
    allowedMetaVarRoles = ['UID','Restrict','Exclude','NumFilter','Unique','Covariate']
    
    try:
        tc = pd.read_table(fn,sep=delimChar,header=None,comment='#')
    except:
        print ("A problem occurred importing the Test-Covariate file:",fn)
        return None

#   File must have 3 columns
    if tc.shape[1] != 3:
        print( 'The Test-Covariate file',fn,' must have 3 columns')
        return None
    
    tc.columns = ['mVar', 'mRole', 'mVals']
    
#   Check to see specified meta variable roles (e.g., Restrict, Covariate) are allowed
    roles = list( tc['mRole'][tc['mRole'].notna()] ) 
    if not all(r in allowedMetaVarRoles  for r in roles) :
        print( 'Second column in Test-Covariate file has a value not among ',allowedMetaVarRoles )
        return None
    
#   Check that any numeric filtering NumF entries have proper syntax
    NumF_df = tc[tc['mRole']=='NumFilter']
    if NumF_df.shape[0] > 0:
        print("checking NumF(s)")
        for k in NumF_df.index:
#            print(NumF_df['mVar'][k], NumF_df['mRole'][k],NumF_df['mVals'][k])
            kVar = NumF_df['mVar'][k]
            kVals =  NumF_df['mVals'][k]
            cutoff = kVals[1:]
            direction = kVals[0]
#            print('cutoff, direction: ',cutoff,direction)
            try: 
                cutnum = pd.to_numeric(cutoff)
            except:
                print ("Cutoff value in NumF statement could not be converted to numeric:",cutoff)
                return None
            if not any(r==direction  for r in ['<','>']):
                print ("NumF statement must contain > or < as first character in 3rd column")
                return None
    
#   
# --- If metaDF is provided, check that all meta vars in Test-Covariate file are in UserMetaData file (includes designated UID variable)
    if metaDF is not None:
        if not all( v in list( metaDF.columns )  for v in list( tc['mVar'] ) ):
            print( 'Variable in Test-Covariate file not in MetaData file' )
            return None
    
    return tc

In [11]:
from TestingCovariatesFunctions2 import importTestCovFile2

In [12]:
metaDF = md1.copy()
print( metaDF.head() )
fn='TestCovList1.txt'
delimChar ='\t'
tc1 = importTestCovFile2(fn,delimChar)
display(tc1)

  SRA_Sample_ID  150-MISTIQ-Cohort Leucegene_Sample_ID  AltAnalyze_ID  \
0     SRS718908              False              04H061  SRS718908.bed
1     SRS718980              False              04H016  SRS718908.bed
2     SRS718910              False              04H061  SRS718910.bed
3     SRS718911              False              07H144  SRS718911.bed
4     SRS718914              False              09H016  SRS718914.bed

  Analyzed_Sets  Tissue_Source    QC Patient_Age Patient_Sex RUNX1_fusions  \
0      Training    Bone marrow  PASS          69           F             0
1      Training    Bone marrow  PASS          70           F         NOVEL
2      Training    Bone marrow  PASS          38           F             0
3      Training    Bone marrow  PASS          53           M         NOVEL
4      Training  Leukapheresis  PASS          64           F           UNK

  PML-RARA_fusions EVI1_fusions
0                0          UNK
1              UNK          UNK
2                0          UNK
3                0          UNK
4                0          UNK

                   mVar      mRole        mVals
0         SRA_Sample_ID        UID          UID
1     150-MISTIQ-Cohort        NaN          NaN
2   Leucegene_Sample_ID     Unique         TRUE
3         AltAnalyze_ID        NaN          NaN
4         Analyzed_Sets    Exclude         Test
5         Tissue_Source        NaN          NaN
6                    QC   Restrict         PASS
7           Patient_Age  NumFilter         > 19
8           Patient_Age  NumFilter          <70
9           Patient_Sex   Restrict         M, F
10        RUNX1_fusions  Covariate  KNOWN,NOVEL
11     PML-RARA_fusions  Covariate    PRESENT,0
12     PML-RARA_fusions  Covariate  PRESENT,UNK
13         EVI1_fusions        NaN          NaN

####  General approach is to create a new metadata object by applying any 
>  filtering specified in 'Restrict', 'Exclude', 'NumFilter' or 'Unique' TestCov rows <br>
>  to the user-supplied metadata file.
####  Then, form sample groups based on Covariates
#####  Note that the actual stat test to be performed is determined elsewhere.

In [13]:
testcov = tc1.copy()
metad = metaDF.copy()
#display( testcov )

filteringRoles = ['Restrict','Exclude','NumFilter','Unique']

tc_filtering = any( r in filteringRoles  for r in list(testcov['mRole']) )

if tc_filtering:
    print('tc has filtering info to apply to metaDF')
else:
    print('tc does NOT have filtering info')

tc has filtering info to apply to metaDF

In [78]:
#display(metad)

In [39]:
def ApplyTestCovToMeta2(tc=None,mt=None):
#    This function applies any filtering specified in tc (pandas dataframe)
#     ['Restrict', 'Exclude', 'NumFilter' or 'Unique'] to mt (pandas dataframe).
#    The new metadata pandas dataframe (filtered as indicated in tc) is returned

    import pandas as pd
    import numpy as np
    
#   Gather TestCovariate (tc) rows with filtering roles
    Restrict_df = tc[tc['mRole']=='Restrict']
    Exclude_df = tc[tc['mRole']=='Exclude']
    NumF_df = tc[tc['mRole']=='NumFilter']
    Unique_df = tc[tc['mRole']=='Unique']
#    X_df = tc[tc['mRole']=='X']
#    print( Restrict_df )
#    print( Exclude_df )
#    print( NumF_df )
#    print( Unique_df )
#    print( X_df )
#    print( X_df.shape)

    fmeta = mt.copy()   
#   Create flag for any meta row to remove
    fmeta['Remov'] = 0
#    print( type( fmeta['Remov'] ) )  
    
#   Handle any RESTRICT filtering
    if Restrict_df.shape[0] > 0:
#        print("handling restrict(s)")
        
        for k in Restrict_df.index:
#    print(Restrict_df['mVar'][k], Restrict_df['mRole'][k],Restrict_df['mVals'][k])
            kVar = Restrict_df['mVar'][k]
            kVals =  Restrict_df['mVals'][k] 
#            print (type(kVals))
            kVals = list( kVals.split(',') ) 
            kVals = list(map(str.strip, kVals))
#            print( 'kVar, kVals: ', kVar, kVals)
#            print ( type (kVals) )
            v = fmeta[kVar]
            remv = np.logical_not( v.isin(kVals) )
#            print( remv )
            fmeta.loc[remv , 'Remov'] = 1
#            print( fmeta)

#   Handle any EXCLUDE filtering
    if Exclude_df.shape[0] > 0:
#        print("handling Exclude(s)")
        
        for k in Exclude_df.index:
#    print(Restrict_df['mVar'][k], Restrict_df['mRole'][k],Restrict_df['mVals'][k])
            kVar = Exclude_df['mVar'][k]
            kVals =  Exclude_df['mVals'][k] 
#            print (type(kVals))
            kVals = list( kVals.split(',') ) 
            kVals = list(map(str.strip, kVals))
#            print( 'kVar, kVals: ', kVar, kVals)
#            print ( type (kVals) )
            v = fmeta[kVar]
            remv =  v.isin(kVals)
#            print( remv )
            fmeta.loc[remv , 'Remov'] = 2
#            print( fmeta)

#   Handle any NumF (numeric) filtering
#     Note that the import function has already checked that direction is either > or <
#      and the (single) value can be coerced to numeric.
#     Example of numeric filtering on an age variable:
#       >19 means keep only samples w/ age > 19
#        coding approach is to remove any records for which age > 19 can not be established

    if NumF_df.shape[0] > 0:
#        print("handling NumF(s)")
        
        for k in NumF_df.index:
#            print(NumF_df['mVar'][k], NumF_df['mRole'][k],NumF_df['mVals'][k])
            kVar = NumF_df['mVar'][k]
            kVals =  NumF_df['mVals'][k] 
#            print (type(kVals))
#            kVals = list( kVals.split(',') ) 
#            kVals = list(map(str.strip, kVals))
#            print( 'kVar, kVals: ', kVar, kVals)
#            print ('type of kVals=', type (kVals) )
            cutoff = kVals[1:]
            direction = kVals[0]
#            print('cutoff, direction: ',cutoff,direction)
#     the following will set any missing or character values to pd.nan            
            numv = pd.to_numeric(fmeta[kVar], errors='coerce')
            cutnum = pd.to_numeric(cutoff)
            
            if direction=='>': 
                kp = numv > cutnum
            else:
                kp = numv < cutnum

#            print('kp',kp)
            fmeta.loc[np.logical_not(kp) , 'Remov'] = 3
#            print( fmeta)

#   Before processing any Unique statements, remove records flagged thus far.
    fmeta = fmeta[fmeta['Remov']==0]          

    if Unique_df.shape[0] > 0:
#        print("handling Unique(s)")
        for k in Unique_df.index:
            kVar = Unique_df['mVar'][k]
            fmeta.drop_duplicates(subset=[kVar], keep='first',inplace=True)
            
 #   Handle any Unique (duplicate removal) filtering       
    fmeta.drop(columns=['Remov'],inplace=True)
    
    return fmeta

In [14]:
from TestingCovariatesFunctions2 import ApplyTestCovToMeta2

In [15]:

#display( testcov )

filtered_meta = ApplyTestCovToMeta2(tc=testcov,mt=metad)

#print( filtered_meta.shape )
display( metad )
display( filtered_meta )

,SRA_Sample_ID,150-MISTIQ-Cohort,Leucegene_Sample_ID,AltAnalyze_ID,Analyzed_Sets,Tissue_Source,QC,Patient_Age,Patient_Sex,RUNX1_fusions,PML-RARA_fusions,EVI1_fusions
0,SRS718908,False,04H061,SRS718908.bed,Training,Bone marrow,PASS,69,F,0,0,UNK
1,SRS718980,False,04H016,SRS718908.bed,Training,Bone marrow,PASS,70,F,NOVEL,UNK,UNK
2,SRS718910,False,04H061,SRS718910.bed,Training,Bone marrow,PASS,38,F,0,0,UNK
3,SRS718911,False,07H144,SRS718911.bed,Training,Bone marrow,PASS,53,M,NOVEL,0,UNK
4,SRS718914,False,09H016,SRS718914.bed,Training,Leukapheresis,PASS,64,F,UNK,0,UNK
5,SRS718915,False,12H042,SRS718915.bed,Training,Heparinised blood,PASS,58,M,NOVEL,UNK,UNK
6,SRS718916,False,11H104,SRS718916.bed,Training,Bone marrow,PASS,56,M,UNK,0,NOVEL
7,SRS718917,False,12H044,SRS718917.bed,Training,Heparinised blood,PASS,,F,0,0,UNK
8,SRS718930,False,04H030,SRS718930.bed,Training,Bone marrow,PASS,50,M,0,0,KNOWN
9,SRS718931,False,05H136,SRS718931.bed,Training,Heparinised blood,PASS,66,,0,0,UNK
10,SRS718933,False,06H115,SRS718933.bed,Training,Heparinised blood,PASS,40,M,0,0,UNK
11,SRS718937,False,11H179,SRS718937.bed,Training,Bone marrow,PASS,22,M,0,0,0
12,SRS718939,False,13H140,SRS718939.bed,Test,Bone marrow,PASS,UNK,UNK,0,0,0
13,SRS718940,False,13H058,SRS718940.bed,Training,Heparinised blood,PASS,44,M,0,0,0
14,SRS718944,False,05H184,SRS718944.bed,Training,Heparinised blood,PASS,48,M,KNOWN,0,UNK
15,SRS718945,False,05H118,SRS718945.bed,Training,Bone marrow,PASS,24,F,KNOWN,PRESENT,UNK
16,SRS718951,False,09H040,SRS718951.bed,Training,Heparinised blood,PASS,35,M,KNOWN,0,UNK
17,SRS718952,False,10H030,SRS718952.bed,Training,Heparinised blood,FAIL,59,M,,0,UNK
18,SRS718955,False,12H045,SRS718955.bed,Test,Bone marrow,PASS,58,M,KNOWN,0,UNK
19,SRS718956,False,12H098,SRS718956.bed,Training,Heparinised blood,PASS,41,M,KNOWN,PRESENT,UNK
20,SRS718957,False,12H166,SRS718957.bed,Training,Heparinised blood,FAIL,51,M,KNOWN,0,UNK
21,SRS718975,False,12H166,SRS718957.bed,Training,Heparinised blood,PASS,51,M,KNOWN,0,UNK
22,SRS718958,False,12H180,SRS718958.bed,Training,Heparinised blood,PASS,38,M,KNOWN,0,NOVEL
23,SRS718959,False,12H183,SRS718959.bed,Training,Heparinised blood,PASS,18,F,KNOWN,0,UNK
24,SRS874618,False,07H009,SRS874618.bed,Training,Heparinised blood,PASS,UNK,NaN,0,0,UNK
25,SRS874619,False,07H005,SRS874619.bed,Training,Heparinised blood,PASS,46,M,0,0,UNK
26,SRS874620,False,06H146,SRS874620.bed,Training,Bone marrow,PASS,45,F,0,PRESENT,KNOWN

,SRA_Sample_ID,150-MISTIQ-Cohort,Leucegene_Sample_ID,AltAnalyze_ID,Analyzed_Sets,Tissue_Source,QC,Patient_Age,Patient_Sex,RUNX1_fusions,PML-RARA_fusions,EVI1_fusions
0,SRS718908,False,04H061,SRS718908.bed,Training,Bone marrow,PASS,69,F,0,0,UNK
3,SRS718911,False,07H144,SRS718911.bed,Training,Bone marrow,PASS,53,M,NOVEL,0,UNK
4,SRS718914,False,09H016,SRS718914.bed,Training,Leukapheresis,PASS,64,F,UNK,0,UNK
5,SRS718915,False,12H042,SRS718915.bed,Training,Heparinised blood,PASS,58,M,NOVEL,UNK,UNK
6,SRS718916,False,11H104,SRS718916.bed,Training,Bone marrow,PASS,56,M,UNK,0,NOVEL
8,SRS718930,False,04H030,SRS718930.bed,Training,Bone marrow,PASS,50,M,0,0,KNOWN
10,SRS718933,False,06H115,SRS718933.bed,Training,Heparinised blood,PASS,40,M,0,0,UNK
11,SRS718937,False,11H179,SRS718937.bed,Training,Bone marrow,PASS,22,M,0,0,0
13,SRS718940,False,13H058,SRS718940.bed,Training,Heparinised blood,PASS,44,M,0,0,0
14,SRS718944,False,05H184,SRS718944.bed,Training,Heparinised blood,PASS,48,M,KNOWN,0,UNK
15,SRS718945,False,05H118,SRS718945.bed,Training,Bone marrow,PASS,24,F,KNOWN,PRESENT,UNK
16,SRS718951,False,09H040,SRS718951.bed,Training,Heparinised blood,PASS,35,M,KNOWN,0,UNK
19,SRS718956,False,12H098,SRS718956.bed,Training,Heparinised blood,PASS,41,M,KNOWN,PRESENT,UNK
21,SRS718975,False,12H166,SRS718957.bed,Training,Heparinised blood,PASS,51,M,KNOWN,0,UNK
22,SRS718958,False,12H180,SRS718958.bed,Training,Heparinised blood,PASS,38,M,KNOWN,0,NOVEL
25,SRS874619,False,07H005,SRS874619.bed,Training,Heparinised blood,PASS,46,M,0,0,UNK
26,SRS874620,False,06H146,SRS874620.bed,Training,Bone marrow,PASS,45,F,0,PRESENT,KNOWN

### Other possible approaches to filtering steps

In [26]:

      
df[“column_name”] = np.where(df[“column_name”]==”some_value”, value_if_true, value_if_false)
df['gender'].mask(df['gender'] == 'female', 0, inplace=True)
      
UserMetaData[kVar] = np.where( UserMetaData[kVar] in kVals,0,1 ) 
      
UserMetaData[kVar] = np.where( UserMetaData[kVar] in kVals,0,1 )      
      
if not all(r in allowedMetaVarRoles  for r in roles) :

True

True

In [63]:
type( kVals )
print(df.isin({'Courses': ['Spark', 'Python']}))

pandas.core.series.Series

In [58]:
student = {
    'Name': ['John', 'Jay', 'sachin', 'Geetha', 'Amutha', 'ganesh'],
    'gender': ['male', 'male', 'male', 'female', 'female', 'male'],
    'math score': [50, 100, 70, 80, 75, 40],
    'test preparation': ['none', 'completed', 'none', 'completed',
                         'completed', 'none'],
}
print( 'Orig') 
# creating a Dataframe object
df = pd.DataFrame(student)
print( df )
print( type(df['gender']) )
  
# Applying the condition
df["gender"] = np.where(df["gender"] == "female", 0, 1)
print(df)
print( type( df['gender'] ) )

print( 'Mod 1')
gv='gender'
df = pd.DataFrame(student)
print( df )
print( type( df[gv]) )
df[gv] = np.where(df[gv] == "female", 0, 1)
print(df)
print( type( df[gv] ) )

print( 'Mod 2')
gv='gender'
valF='female'
df = pd.DataFrame(student)
print( df )
print( 'type of gv col ',type( df[gv]) )
print( 'type of valF ',type(valF))
df[gv] = np.where(df[gv] == valF, 0, 1)
print(df)
print( type( df[gv] ) )


print( 'Mod 3')
gv='gender'
valF=set('female')
df = pd.DataFrame(student)
print( df )
print( 'type of gv col ',type( df[gv]) )
print( 'type of valF ',type(valF))
#df[gv] = np.where(df[gv] in valF, 0, 1)
print(df)
print( type( df[gv] ) )


print( 'Mod 4')
gv='gender'
valF=set('female')
df = pd.DataFrame(student)
print( df )
print( 'type of gv col ',type( df[gv]) )
print( 'type of valF ',type(valF))
#df[gv] = (df[gv]).where(df[gv] in valF , 1)
print(df)
print( type( df[gv] ) )
#df['col'] = (value_if_false).where(condition, value_if_true)
#df['A'] = (df['A'] / 2).where(df['A'] < 20, df['A'] * 2)

print( df[gv]=='female')
t1 = pd.Series( df[gv] in valF )
print( t1 )

######
s = pd.Series(['lama', 'cow', 'lama', 'beetle', 'lama',
               'hippo'], name='animal')
s.isin(['cow', 'lama'])
0     True
1     True
2     True
3    False
4     True
5    False
Name: animal, dtype: bool

~s.isin(['cow', 'lama'])

Orig
     Name  gender  math score test preparation
0    John    male          50             none
1     Jay    male         100        completed
2  sachin    male          70             none
3  Geetha  female          80        completed
4  Amutha  female          75        completed
5  ganesh    male          40             none
<class 'pandas.core.series.Series'>
     Name  gender  math score test preparation
0    John       1          50             none
1     Jay       1         100        completed
2  sachin       1          70             none
3  Geetha       0          80        completed
4  Amutha       0          75        completed
5  ganesh       1          40             none
<class 'pandas.core.series.Series'>
Mod 1
     Name  gender  math score test preparation
0    John    male          50             none
1     Jay    male         100        completed
2  sachin    male          70             none
3  Geetha  female          80        completed
4  Amutha  female          75        completed
5  ganesh    male          40             none
<class 'pandas.core.series.Series'>
     Name  gender  math score test preparation
0    John       1          50             none
1     Jay       1         100        completed
2  sachin       1          70             none
3  Geetha       0          80        completed
4  Amutha       0          75        completed
5  ganesh       1          40             none
<class 'pandas.core.series.Series'>
Mod 2
     Name  gender  math score test preparation
0    John    male          50             none
1     Jay    male         100        completed
2  sachin    male          70             none
3  Geetha  female          80        completed
4  Amutha  female          75        completed
5  ganesh    male          40             none
type of gv col  <class 'pandas.core.series.Series'>
type of valF  <class 'str'>
     Name  gender  math score test preparation
0    John       1          50             none
1     Jay       1         100        completed
2  sachin       1          70             none
3  Geetha       0          80        completed
4  Amutha       0          75        completed
5  ganesh       1          40             none
<class 'pandas.core.series.Series'>
Mod 3
     Name  gender  math score test preparation
0    John    male          50             none
1     Jay    male         100        completed
2  sachin    male          70             none
3  Geetha  female          80        completed
4  Amutha  female          75        completed
5  ganesh    male          40             none
type of gv col  <class 'pandas.core.series.Series'>
type of valF  <class 'set'>
     Name  gender  math score test preparation
0    John    male          50             none
1     Jay    male         100        completed
2  sachin    male          70             none
3  Geetha  female          80        completed
4  Amutha  female          75        completed
5  ganesh    male          40             none
<class 'pandas.core.series.Series'>
Mod 4
     Name  gender  math score test preparation
0    John    male          50             none
1     Jay    male         100        completed
2  sachin    male          70             none
3  Geetha  female          80        completed
4  Amutha  female          75        completed
5  ganesh    male          40             none
type of gv col  <class 'pandas.core.series.Series'>
type of valF  <class 'set'>
     Name  gender  math score test preparation
0    John    male          50             none
1     Jay    male         100        completed
2  sachin    male          70             none
3  Geetha  female          80        completed
4  Amutha  female          75        completed
5  ganesh    male          40             none
<class 'pandas.core.series.Series'>
0    False
1    False
2    False
3     True
4     True
5    False
Name: gender, dtype: bool

TypeError: unhashable type: 'Series'